services:
  - type: web
    name: dino-challenge-bot-api
    runtime: python
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: ORGANIZER_CHAT_ID
        sync: false
      - key: PAYPAL_CLIENT_ID
        sync: false
      - key: PAYPAL_SECRET_KEY
        sync: false
      - key: PAYPAL_MODE
        value: live
      - key: GAME_URL
        value: https://nox-archeo.github.io/dinochallenge/
      - key: PYTHON_VERSION
        value: 3.10.13
    plan: free
    healthCheckPath: /health
    autoDeploy: true
